"""initial with piostgres

Revision ID: c1e06b0e3f10
Revises: 
Create Date: 2018-02-07 14:13:56.466838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e06b0e3f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radwomen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_name', sa.String(length=80), nullable=False),
    sa.Column('wiki_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wiki_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radwomen')
    # ### end Alembic commands ###
